# Generated by Django 5.0.9 on 2024-11-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagepage",
            name="thumbnail_image_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
