# Generated by Django 5.0.9 on 2024-11-30 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_imagepage_thumbnail_image_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagepage",
            name="thumbnail_image_id",
        ),
    ]
