# Generated by Django 5.0.9 on 2025-01-28 18:31

from django.db import migrations

def remove_initial_wagtail_data(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    Page = apps.get_model("wagtailcore.Page")
    Site = apps.get_model("wagtailcore.Site")

    root_page = Page.objects.get(
        title="Root",
        slug="root",
        path="0001",
        numchild=1,
        url_path="/",
    )

    content_type = ContentType.objects.filter(
        model="page",
        app_label="wagtailcore"
    )

    homepage = Page.objects.get(
        title="Welcome to your new Wagtail site!",
        slug="home",
        path="00010001",
        depth=2,
    )

    site = Site.objects.get(
        hostname="localhost",
        root_page=root_page,
        is_default_site=True,
    )

    homepage.delete()
    root_page.delete()
    site.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_imagepage_thumbnail_image"),
    ]
    operations = [
        migrations.RunPython(remove_initial_wagtail_data),
    ]