# Generated by Django 5.0.9 on 2025-01-28 18:31

from django.db import migrations


def replace_initial_wagtail_data(apps, schema_editor):
    Page = apps.get_model("wagtailcore.Page")
    Site = apps.get_model("wagtailcore.Site")

    try:
        root_page = Page.objects.get(
            pk=1,
            title="Root",
            slug="root",
            path="0001",
            numchild=1,
            url_path="/",
        )
    except Page.DoesNotExist:
        return

    homepage = Page.objects.get(
        title="Welcome to your new Wagtail site!",
        slug="home",
        path="00010001",
        depth=2,
    )

    site = Site.objects.get(
        pk=1,
        hostname="localhost",
        is_default_site=True,
    )

    homepage.title = "Content will be here soon"
    root_page.title = "Juurisivu"
    site.hostname = "localhost"

    homepage.save()
    root_page.save()
    site.save()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_imagepage_thumbnail_image"),
    ]
    operations = [
        migrations.RunPython(replace_initial_wagtail_data),
    ]